Vagrant.configure("2") do |config|
  config.vm.define "vmun" do |vmun|
   vmun.vm.box = "hashicorp/bionic64"
   vmun.vm.hostname = "vmun"
   vmun.vm.network "private_network", ip: "192.168.33.2"
  end
  config.vm.define "vmdeux" do |vmdeux|
   vmdeux.vm.box = "hashicorp/bionic64"
   vmdeux.vm.hostname = "vmdeux"
   vmdeux.vm.network "private_network", ip: "192.168.33.3"
  end
end
